services:
  backend:
    container_name: ct-apps-mikail
    build: ./app
    image: muhammadmikialj/apps-mikail
    restart: always
    ports:
    - "5000:3000"
    volumes:
    - app-data:/app/public/images
volumes:
  app-data:
