services:
  backend:
  cotnainer_name: ct-apps-mikail
    build: ./app
    iamge: muhammadmikialj/apps-mikail
    restart: always
    ports:
    - "3000:3000"
    volumes:
    - app-data:/app/public/images
  volumes:
    app-data:
